### ISSUE TITLE
Task 3 - Obstacles

### ISSUE THREAD

**Issue by minhd-vu** [minhd-vu/sdl-level-loading#3]
- [x] Create at least one sprite or a geometric shape object, which the agents will bounce off when they collide
- [x] Spawn multiple of these objects randomly

**Comment by minhd-vu** [comment]
Will likely have to implement in these functions in `MyAgent.cpp`
```
void MyChickenAgent::handle_event(SDL_Event &e)
// or
void MyChickenAgent::update(MyAgent *player, std::list<MyChickenAgent *> enemies)
```

**Comment by rrobergmu** [comment]
I replicated ZombieAgent, named MyCloudAgent with vertical features as opposed to horizontal ones. Also replaced some of the header info such as renaming 'left' to 'up' 
Header:
`class MyCloudAgent : public MyAgent
    {
    public:
        MyCloudAgent(bool movable = true, bool collision = true)
            :MyAgent(movable, collision) {
            orig_y = INT_MAX; up = true; collide_with = NULL;
        }
        virtual void update();
        virtual void display();
        virtual void handle_event(SDL_Event& e);
    private:
        int orig_y;
        bool up;
        MyAgent* collide_with;
        int collision_free_timer = 10;
    };`

MyAgent.cpp:
`// CUSTOM CLOUD AGENT
  void MyCloudAgent::display()
  {
      if (!this->visible) return; //not visible...
      //setup positions and ask sprite to draw something
      this->sprite->display(x, y, scale, degree, NULL, this->up ? SDL_FLIP_NONE : SDL_FLIP_HORIZONTAL);
      draw_bounding_box();
  }

  void MyCloudAgent::update()
  {
      if (!this->collision)
      {
          if (collision_free_timer >= 0) this->collision_free_timer--;
          else collide_with = NULL; //no collision
      }

      this->collision = false;

      if (orig_y == INT_MAX)
          orig_y = y;
      if (up) y -= 2;
      else y += 2;
      if (y < orig_y - 100) up = false;
      if (y > orig_y + 100) up = true;
  }

  void MyCloudAgent::handle_event(SDL_Event& e)
  {
      //return;
      if (this->collision && collide_with != NULL)
      {
          //std::cout<<"already in collision with "<<collide_with<<std::endl;

          return;
      }

      if (e.type == SDL_USEREVENT)
      {
          if (e.user.code == 1)
          {
              if (e.user.data1 == this || e.user.data2 == this)
              {
                  MyAgent* other = (MyAgent*)((e.user.data1 != this) ? e.user.data1 : e.user.data2);

                  if (other != collide_with)
                  {
                      collide_with = other;
                      up = !up;
                  }
                  this->collision_free_timer = 10;
                  this->collision = true;
              }
              //else collide_with=NULL; //no collision
          }
      }
  }`

**Comment by rrobergmu** [comment]
I replicated ZombieAgent, named MyCloudAgent with vertical features as opposed to horizontal ones. Also replaced some of the header info such as renaming 'left' to 'up'
Header:
```
class MyCloudAgent : public MyAgent
    {
    public:
        MyCloudAgent(bool movable = true, bool collision = true)
            :MyAgent(movable, collision) {
            orig_y = INT_MAX; up = true; collide_with = NULL;
        }
        virtual void update();
        virtual void display();
        virtual void handle_event(SDL_Event& e);
    private:
        int orig_y;
        bool up;
        MyAgent* collide_with;
        int collision_free_timer = 10;
    };
```

MyAgent.cpp:
```
// CUSTOM CLOUD AGENT
  void MyCloudAgent::display()
  {
      if (!this->visible) return; //not visible...
      //setup positions and ask sprite to draw something
      this->sprite->display(x, y, scale, degree, NULL, this->up ? SDL_FLIP_NONE : SDL_FLIP_HORIZONTAL);
      draw_bounding_box();
  }

  void MyCloudAgent::update()
  {
      if (!this->collision)
      {
          if (collision_free_timer >= 0) this->collision_free_timer--;
          else collide_with = NULL; //no collision
      }

      this->collision = false;

      if (orig_y == INT_MAX)
          orig_y = y;
      if (up) y -= 2;
      else y += 2;
      if (y < orig_y - 100) up = false;
      if (y > orig_y + 100) up = true;
  }

  void MyCloudAgent::handle_event(SDL_Event& e)
  {
      //return;
      if (this->collision && collide_with != NULL)
      {
          //std::cout<<"already in collision with "<<collide_with<<std::endl;

          return;
      }

      if (e.type == SDL_USEREVENT)
      {
          if (e.user.code == 1)
          {
              if (e.user.data1 == this || e.user.data2 == this)
              {
                  MyAgent* other = (MyAgent*)((e.user.data1 != this) ? e.user.data1 : e.user.data2);

                  if (other != collide_with)
                  {
                      collide_with = other;
                      up = !up;
                  }
                  this->collision_free_timer = 10;
                  this->collision = true;
              }
              //else collide_with=NULL; //no collision
          }
      }
  }
```
